---
name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Generate Token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          app-id: '${{ secrets.BOT_APP_ID }}'
          private-key: '${{ secrets.BOT_APP_PRIVATE_KEY }}'

      - name: Generate Release
        uses: mirceanton/action-semver-release@c3a662afb3fb4a008b8992d73067d8f00c865ad0 # v3.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
